### ISSUE TITLE
Could the rosbag file called “”sports_fileds.bag“”   be  applied for VINS-MONO?

### ISSUE THREAD

**Issue by yangnan456** [HKUST-Aerial-Robotics/GVINS-Dataset#12]
I apply the sport_filled.bag for VINS-mono .but when I requeie `roslaunch vins_estimator euroc.launch `the teminal showed 
![image](https://user-images.githubusercontent.com/99865141/220573291-357b1e3e-b79a-4266-8566-81f24b95cc31.png)
I want to ask this  `.bag ` file whether could be apply for vins-mono?

**Comment by shaozu** [comment]
Hi, @yangnan456. You may need to adjust the IMU parameters to make it work with VINS-mono. Please refer to [this file](https://github.com/HKUST-Aerial-Robotics/GVINS/blob/main/config/visensor_f9p/visensor_left_f9p_config.yaml) if you're still interested.
