### ISSUE TITLE
about the rtk covariance matrix of the rosbag

### ISSUE THREAD

**Issue by YingJieFan2001** [HKUST-Aerial-Robotics/GVINS-Dataset#14]
Thank you very much for making the dataset publicly available. However, I noticed that in the rosbag, the covariance matrix of the RTK positioning results is all zeros.
Is this the original solution, or is it not supposed to be like this? If possible, could you provide the rtk
 covariance matrix?
![image](https://github.com/HKUST-Aerial-Robotics/GVINS-Dataset/assets/116481272/67179405-1afc-4d8c-ae12-379c28a4d189)

**Comment by shaozu** [comment]
Hi, @YingJieFan2001. Unfortunately the receiver does not provide this kind of information. However, you may refer to the [GnssPVTSolnMsg](https://github.com/HKUST-Aerial-Robotics/gnss_comm/blob/main/msg/GnssPVTSolnMsg.msg) message for horizontal and vertical accuracy.
