### ISSUE TITLE
The Meaning of the Data in the /ublox_driver/receiver_lla Topic

### ISSUE THREAD

**Issue by Tis-Wu** [HKUST-Aerial-Robotics/GVINS-Dataset#17]
Is the /ublox_driver/receiver_lla topic in the rosbag data the real ground position obtained from RTK processing, or is it the receiver's own rough computed position?

**Comment by shaozu** [comment]
Hi @Tis-Wu, the `/ublox_driver/receiver_lla` is the receiver computed position, but it may not be rough. The ublox F9P has a internal RTK engine and the accuracy of computed position may vary depends on the environment. If it got RTK fixed solution, the accuracy is usually centimeter-level (`real ground position`), or else the error could go to servel meters (`rough computed position`). If you need to know whether it is fixed or not, you may refer to the topic `/ublox_driver/receiver_pvt` and its [definition](https://github.com/HKUST-Aerial-Robotics/gnss_comm/blob/main/msg/GnssPVTSolnMsg.msg).

**Comment by EmmanuelMess** [comment]
> Hi [@Tis-Wu](https://github.com/Tis-Wu), the `/ublox_driver/receiver_lla` is the receiver computed position, but it may not be rough. The ublox F9P has a internal RTK engine and the accuracy of computed position may vary depends on the environment. If it got RTK fixed solution, the accuracy is usually centimeter-level (`real ground position`), or else the error could go to servel meters (`rough computed position`). If you need to know whether it is fixed or not, you may refer to the topic `/ublox_driver/receiver_pvt` and its [definition](https://github.com/HKUST-Aerial-Robotics/gnss_comm/blob/main/msg/GnssPVTSolnMsg.msg?rgh-link-date=2024-12-05T03%3A22%3A56.000Z).

Is it possible to get the differential GNSS and non differential GNSS for the same timestamps?
