### ISSUE TITLE
Convert error

### ISSUE THREAD

**Issue by impce-lg** [HKUST-Aerial-Robotics/GVINS-Dataset#2]
Here is my modification:
-----------
#define INPUT_BAG_FILEPATH "/home/XXXX/GVINS/sports_field/sports_field.bag"
#define OUTPUT_RINEX_FILEPATH "/home/XXXX/GVINS/sports_field/"
-----------
and it reports error:
---------
rosrun gvins_dataset_toolkit bag2rinex 
段错误 (核心已转储)
---------

**Comment by shaozu** [comment]
Hi, @huanhexiao. You may need to define the `OUTPUT_RINEX_FILEPATH` macro as `"/home/XXXX/GVINS/sports_field/sports_field.rnx"`.

**Comment by impce-lg** [comment]
> Hi, @huanhexiao. You may need to define the `OUTPUT_RINEX_FILEPATH` macro as `"/home/XXXX/GVINS/sports_field/sports_field.rnx"`.

Thanks，this does not work either.
I have figured it out in another way
Thx again

**Comment by impce-lg** [comment]
Hi@shaozu , another question:
I use **bag2rinex** getting the v3.04 obs file **sport.21o**, whose time can be transfered to gpstime .
I also extract the png fold **cam1/** whose files named with timestamp , from bag file.
the var "gnss_local_time_diff: 18.0" associates the above two timestamp, right?

**Comment by shaozu** [comment]
Yes.

**Comment by impce-lg** [comment]
> Yes.

A late thanks and best wish to u.
