### ISSUE TITLE
Can you provide the ROS code for recording Ublox GPS raw data?

### ISSUE THREAD

**Issue by JiangZhengok** [HKUST-Aerial-Robotics/GVINS-Dataset#3]
Thank you very much for your work. Can you provide the ROS code for recording Ublox GPS raw data?

**Comment by shaozu** [comment]
Hi, @JiangZhengok. I will release that part of code in this week.

**Comment by JiangZhengok** [comment]
@shaozu Thanks for your help. I have never used GPS raw data. It took me a week to write the parsing code by reading the Ublox datasheet, but there are still some differences with yours.

**Comment by shaozu** [comment]
Hi, @JiangZhengok. The code is released at [ublox_driver repo](https://github.com/HKUST-Aerial-Robotics/ublox_driver).

**Comment by JiangZhengok** [comment]
> Hi, @JiangZhengok. The code is released at [ublox_driver repo](https://github.com/HKUST-Aerial-Robotics/ublox_driver).
Thanks for your help.
