### ISSUE TITLE
How to set the frequency of PPS signal to 0.2 Hz by u-center?

### ISSUE THREAD

**Issue by JiangZhengok** [HKUST-Aerial-Robotics/GVINS-Dataset#4]
You mentioned that in the README：
1. The GNSS receiver reports the time information of next PPS signal. In our system the reporting frequency is set to 1Hz.
2. The PPS signal from the GNSS receiver is used to trigger the external interrupt of VI-Sensor. In our system the frequency of PPS is set to 0.2 Hz.
Did you set that by u-center as below？
![image](https://user-images.githubusercontent.com/34699594/119504228-5a283900-bd9e-11eb-9183-b53271626ac8.png)
But I don't know how to set the frequency of PPS signal to 0.2 Hz. And how to set the reporting frequency to 1Hz?

**Comment by JiangZhengok** [comment]
It is only allowed to be set at >= 1Hz。

**Comment by shaozu** [comment]
Hi, @JiangZhengok. You can set the period of PPS to 5s. Select the `Period` option on the right part and then you should be able to input the period.

**Comment by JiangZhengok** [comment]
> Hi, @JiangZhengok. You can set the period of PPS to 5s. Select the `Period` option on the right part and then you should be able to input the period.

Yes, you are right. I note that 5 identical PPS output per 5 second in your rosbag, but 50 identical PPS output per 5 second in my bag. So I think my PPS output frequency is set incorrectly（10Hz）. 
![image](https://user-images.githubusercontent.com/34699594/119596421-ac567200-be11-11eb-93e1-2f751a9712e9.png)
I set RXM and NAV output frequency by follow, 
![E093C96B-AE5C-4c6b-865B-09AB5AD9A9A7](https://user-images.githubusercontent.com/34699594/119593909-6e574f00-be0d-11eb-863a-199bc66a6fea.png)
but that also set PPS output frequency to 10Hz. How can I only set PPS output frequency to 1Hz?

**Comment by shaozu** [comment]
I set the TP parameter in `u-center->view->Generation 9 Configuration View->Advanced Configuration->CFG-TP`. You may refer to Section 3.11 of [ZED-F9P_IntegrationManual_(UBX-18010802)](https://www.u-blox.com/sites/default/files/ZED-F9P_IntegrationManual_%28UBX-18010802%29.pdf) for more details.

**Comment by JiangZhengok** [comment]
> I set the TP parameter in `u-center->view->Generation 9 Configuration View->Advanced Configuration->CFG-TP`. You may refer to Section 3.11 of [ZED-F9P_IntegrationManual_(UBX-18010802)](https://www.u-blox.com/sites/default/files/ZED-F9P_IntegrationManual_%28UBX-18010802%29.pdf) for more details.

All right. I find that u-center user guide have mentioned that Generation 9 Configuration View can only be used to configure u-blox 9 generation receivers. But my ublox is NEO-M8P.

Thanks for your help.

**Comment by shaozu** [comment]
You're welcome. Then I guess you can find the way in NEO-M8P integration manual. BTW, the TP setting does not matter if you do not perform hardware synchronization.
