### ISSUE TITLE
error opening .bag file

### ISSUE THREAD

**Issue by haibo9916** [HKUST-Aerial-Robotics/GVINS-Dataset#5]
I tried to use the gvins-dataset toolbox to convert GNSS raw data to RINEX file format, but there was no prompt Bag file failed to open. I don't know why? Similarly, saving RTK solution as CSV file also failed. It is worth noting that my file uses the data source provided in gvins
![image](https://user-images.githubusercontent.com/65943417/149653706-1a522f9b-045d-42c1-8090-ff88808b1238.png)
这是我的输入信息
![image](https://user-images.githubusercontent.com/65943417/149653744-e7ef0a2a-b59d-41bf-b324-4492ad298606.png)

**Comment by haibo9916** [comment]
I tried to use the gvins-dataset toolbox to convert GNSS raw data to RINEX file format, but there was no prompt Bag file failed to open. I don't know why? Similarly, saving RTK solution as CSV file also failed. 
# This is my ROS feature pack:
![image](https://user-images.githubusercontent.com/65943417/149716802-94e7be5d-45ac-4fe1-917d-89407bae9dbf.png)
# my bag2rinex.cpp
![image](https://user-images.githubusercontent.com/65943417/149716968-57f00476-ac14-4a9c-9364-ec56144dbd27.png)
# sports_field.bag
![image](https://user-images.githubusercontent.com/65943417/149717064-05e64c86-cc16-44a6-821c-70fb983bc745.png)
# result
![image](https://user-images.githubusercontent.com/65943417/149717555-61d5ce69-d95a-4da3-869f-a17994575801.png)

**I tried to clone the gvins dataset project directly or take out the toolkit folder separately, but failed**
# I don't know why. Who can help me?

**Comment by shaozu** [comment]
Hey @haibo9916. Sorry for the late reply. You may replace the relative filepath with the absolute one and see if it works.

**Comment by haibo9916** [comment]
@shaozu Sorry, I used the absolute path, but the code still makes mistakes.Teacher, do you have any other solutions?

**Comment by shaozu** [comment]
Then check the memory usage.
