### ISSUE TITLE
Urban driving data

### ISSUE THREAD

**Issue by Mahmoudadham4040** [HKUST-Aerial-Robotics/GVINS-Dataset#6]
could you please upload the urban driving data?

**Comment by haibo9916** [comment]
urban driving data?There are only two datasets, "sports_field" and "complex_environment"

**Comment by haibo9916** [comment]
urban driving data?There are only two datasets, "sports_field" and "complex_environment"

**Comment by Mahmoudadham4040** [comment]
Thank you for your response.
 I ask you for the "Urban Driving Experiment Data" which test the system with a challenging urban driving scenario in one
 of HK districts .
     On Wednesday, January 26, 2022, 12:51:46 PM GMT+8, haibo9916 ***@***.***> wrote:  
 
 


urban driving data?There are only two datasets, "sports_field" and "complex_environment"

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shaozu** [comment]
Hi @Mahmoudadham4040. Sure, I will release this dataset these days.

**Comment by shaozu** [comment]
FYI. The urban_driving dataset has been uploaded.
