### ISSUE TITLE
alpha and eta values for the MEI model

### ISSUE THREAD

**Issue by mcamurri** [HKUST-Aerial-Robotics/GVINS-Dataset#8]
Hi all,
I'm not particularly familiar with the MEI camera model, so I had a look at the paper first.

It seems the matrix K depends on two parameters that are not provided by the yaml: alpha (required to get the skew) and eta, which depends on the parametric curve used.

What assumptions have been made for alpha and eta? 
Can in first approximation assume alpha = 0 and  eta = -1?

Thanks,
Marco.

**Comment by shaozu** [comment]
Hi, @mcamurri. The misalignment is ignored so alpha is assumed to be zero. The parameter eta is mixed with the focal length parameters implicitly. BTW, you can use [camodocal](https://github.com/hengli/camodocal) to handle the camera models.
